### ISSUE TITLE
Can you add example of doing this with GDB on say, an ubuntu or alpine container?

### ISSUE THREAD

**Issue by LeeRuns** [andyneff/hello-world-gdb#2]

**Comment by wkaisertexas** [comment]
@andyneff This would be great. I also would like more clarification on how this works under the hood. Looking to implement pipe transport with apptainer and ros and I currently have my client freeze each time it is run.

**Comment by JonnyBnice84** [comment]
> _No description provided._

README.md

**Comment by andyneff** [comment]
> @andyneff This would be great. I also would like more clarification on how this works under the hood. Looking to implement pipe transport with apptainer and ros and I currently have my client freeze each time it is run.

Unfortuantely, the nature of singularity is fundamentally different. I don't know off hand of a way to execute a second executable in the same container space as the one you run with `run`/`exec`/`instance start`/`instance run`. All other command.

I tried a little to get apptainer to work by using `gdb` from the host, however VSCode didn't like setting the `pipeProgram` to `bash` or `/usr/bin/env`. `bash` was close, but I started getting bogus line widths of like 100k+. So I took a gamble and used this:

```
          "pipeProgram": "script",
          "pipeArgs": [
              "-q",
              "/dev/null",
              "-c",
          ],
```

**Does not work for me**

```
touch /tmp/hello.out
apptainer run --add-caps SYS_PTRACE -B /tmp/hello.out:/tmp/hello.out ./hello-world-gdb_ubuntu.sif
```

And that was enough to get VSCode happy enough to launch `ps` and `gdb` now, however GDB and the executable would just freeze. So I ultimately made no progress.

**Comment by andyneff** [comment]
Update main branch to have alpine and ubuntu examples.

Here's a reference for how it works: https://code.visualstudio.com/docs/cpp/pipe-transport
